# !!!!!!!!!!! NOT FUNCTIONAL DO NOT RUN !!!!!!!!!!!

# This Makefile is used to build the SPI Sniffer interface for Wireshark.
# It installs:
# - the configuration profile accessibly through Edit -> Configuration Profiles
# - the dissector plugin
# - the extcap interface

